# Generated by Django 4.1.7 on 2023-02-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='preview_img_url',
        ),
        migrations.AddField(
            model_name='project',
            name='preview_img',
            field=models.ImageField(blank=True, upload_to='project_previews/'),
        ),
    ]
